---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2021-04-15T08:16:15.581555022Z"
  name: instavote
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1h
  ref:
    branch: main
  timeout: 20s
  secretRef:
    name: github-instavote
  url: https://github.com/dopsdemo/instavote.git

