---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2021-04-24T08:51:40.014685699Z"
  name: result
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: instavote
  commit:
    authorEmail: flux@example.com
    authorName: flux
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  push:
    branch: main
  update:
    path: ./helm/charts/result
    strategy: Setters

