---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: result
  namespace: instavote
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: instavote-deploy
  commit:
    authorEmail: flux@example.com
    authorName: flux
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  push:
    branch: main
  update:
    path: ./helm/charts/result
    strategy: Setters

