---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: instavote-all
  namespace: instavote
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: instavote-deploy
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  push:
    branch: main
  update:
    path: ./kustomize/vote/staging
    strategy: Setters

