---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2021-04-24T04:55:31.400215379Z"
  name: instavote-all
  namespace: flux-system
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: instavote
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
  interval: 1m0s
  push:
    branch: main
  update:
    path: ./kustomize/vote/staging
    strategy: Setters

