apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 7
images:
- name: schoolofdevops/vote # {"$imagepolicy": "flux-system:vote:repository"}
  newTag: main-e8b357e3-1619193658 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "sre@example.com"
configMapGenerator:
- name: vote-options
  envs:
  - options.env
